### ISSUE TITLE
Inline mode

### ISSUE THREAD

**Issue by bosbyj** [demisx/sublime-vim-navigation#1]
Is there a way to make it work exactly like in VIM?

If the cursor is in the very beginning of a line, press "alt+h" and the cursor is supposed to be stop right there, instead of going up to the endpoint of the upper line.

I have read the api, but still haven't figured a way to fix this.

**Comment by demisx** [comment]
Do you mean don't jump on the previous line when moving the cursor left?

**Comment by bosbyj** [comment]
Hi Dmitri,

Yes I do. As you can see in vintage mode, the cursor stops when you hit the
left margin.
I dived into the source of vintage plugin, but couldn't figure out how it
worked that way.

Bos

**Comment by demisx** [comment]
Yeah, doesn't look like there is a straightforward way to do this. Maybe there will be in the future updates, if they ever come. Honestly, I no longer use SublimeText 3 due to it not being supported.

**Comment by bosbyj** [comment]
Thank you Dmitri : )
